/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mb.view.forms;

import javax.swing.JOptionPane;
import org.mb.controller.CustomerDAO;
import org.mb.model.Customer;
import org.mb.view.panels.CustomerPanel;

/**
 *
 * @author QWERTY
 */
public class CustomerForm extends javax.swing.JDialog {

    CustomerPanel cp;
    Customer cob;
    private static final String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
            + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

    public void setCustomerPanel(CustomerPanel cp) {
        this.cp = cp;
    }

    public void setCustomer(Customer cob) {
        this.cob = cob;

        jTextField_CustomerID.setText(cob.getCustomer_id() + "");
        jTextField_Name.setText(cob.getName());
        jTextField_Address.setText(cob.getAddress());
        jTextField_Phone.setText(cob.getPhone() + "");
        jTextField_Email.setText(cob.getEmail());
    }

    /**
     * Creates new form CustomerForm
     */
    public CustomerForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        if (cob == null) {
            jLabel_ID.setVisible(false);
            jTextField_CustomerID.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_ID = new javax.swing.JLabel();
        jTextField_CustomerID = new javax.swing.JTextField();
        jTextField_Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Address = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Phone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton_SaveCustomer = new javax.swing.JButton();
        jLabel_NameError = new javax.swing.JLabel();
        jLabel_AddressError = new javax.swing.JLabel();
        jLabel_PhoneError = new javax.swing.JLabel();
        jLabel_EmailError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Customer Form");

        jLabel_ID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_ID.setText("ID :");

        jTextField_CustomerID.setEditable(false);
        jTextField_CustomerID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField_Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_NameKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Name :");

        jTextField_Address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_AddressKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Address :");

        jTextField_Phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_PhoneKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Phone :");

        jTextField_Email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_EmailKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Email :");

        jButton_SaveCustomer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_SaveCustomer.setText("SAVE");
        jButton_SaveCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveCustomerActionPerformed(evt);
            }
        });

        jLabel_NameError.setForeground(java.awt.Color.red);
        jLabel_NameError.setText(" ");

        jLabel_AddressError.setForeground(java.awt.Color.red);
        jLabel_AddressError.setText(" ");

        jLabel_PhoneError.setForeground(java.awt.Color.red);
        jLabel_PhoneError.setText(" ");

        jLabel_EmailError.setForeground(java.awt.Color.red);
        jLabel_EmailError.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_SaveCustomer)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_AddressError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_NameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_Address, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_PhoneError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_Phone, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_ID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_CustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_EmailError, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ID)
                    .addComponent(jTextField_CustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_NameError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_AddressError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_PhoneError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_EmailError)
                .addGap(5, 5, 5)
                .addComponent(jButton_SaveCustomer)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SaveCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveCustomerActionPerformed
        //check errors
        if (!(jLabel_NameError.getText().equals(" ")
                && jLabel_AddressError.getText().equals(" ")
                && jLabel_PhoneError.getText().equals(" ")
                && jLabel_EmailError.getText().equals(" "))) {
            JOptionPane.showMessageDialog(null, "Sorry there are errors in the form");
            return;
        }
        if (jTextField_Name.getText().equals("")
                || jTextField_Address.getText().equals("")
                || jTextField_Phone.getText().equals("")
                || jTextField_Email.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all the fields first");
            return;
        }
        if (cob == null) {
            if (new CustomerDAO().checkPhone(jTextField_Phone.getText())) {
                JOptionPane.showMessageDialog(null, "Sorry the phone number is taken");
                return;
            }
            if (new CustomerDAO().checkEmail(jTextField_Email.getText())) {
                JOptionPane.showMessageDialog(null, "Sorry the email is taken");
                return;
            }
        }
        

        //get input values
        String name = jTextField_Name.getText();
        String address = jTextField_Address.getText();
        long phone = Long.parseLong(jTextField_Phone.getText());
        String email = jTextField_Email.getText();

        //set input values into model class "Customer" object
        Customer ob = new Customer();
        ob.setName(name);
        ob.setAddress(address);
        ob.setPhone(phone);
        ob.setEmail(email);

        //handover this model object to controller class "CustomerDAO"
        CustomerDAO cDAO = new CustomerDAO();
        if (cob == null) {
            cDAO.addCustomer(ob);
        } else {
            ob.setCustomer_id(cob.getCustomer_id());
            cDAO.updateCustomer(ob);
        }

        cp.loadData();
        dispose();
    }//GEN-LAST:event_jButton_SaveCustomerActionPerformed

    private void jTextField_NameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NameKeyReleased
        if (jTextField_Name.getText().equals("")) {
            jLabel_NameError.setText("Name cant be empty");
        } else {
            jLabel_NameError.setText(" ");
        }
    }//GEN-LAST:event_jTextField_NameKeyReleased

    private void jTextField_AddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_AddressKeyReleased
        if (jTextField_Address.getText().equals("")) {
            jLabel_AddressError.setText("Address cant be empty");
        } else {
            jLabel_AddressError.setText(" ");
        }
    }//GEN-LAST:event_jTextField_AddressKeyReleased

    private void jTextField_PhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PhoneKeyReleased

        try {
            long x = Long.parseLong(jTextField_Phone.getText());
            jLabel_PhoneError.setText(" ");
        } catch (Exception ex) {
            jLabel_PhoneError.setText("Invalid Phone number");
        }
    }//GEN-LAST:event_jTextField_PhoneKeyReleased

    private void jTextField_EmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_EmailKeyReleased
        if (!jTextField_Email.getText().matches(EMAIL_PATTERN)) {
            jLabel_EmailError.setText("Invalid Email");
        } else {
            jLabel_EmailError.setText(" ");
        }
    }//GEN-LAST:event_jTextField_EmailKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomerForm dialog = new CustomerForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_SaveCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_AddressError;
    private javax.swing.JLabel jLabel_EmailError;
    private javax.swing.JLabel jLabel_ID;
    private javax.swing.JLabel jLabel_NameError;
    private javax.swing.JLabel jLabel_PhoneError;
    private javax.swing.JTextField jTextField_Address;
    private javax.swing.JTextField jTextField_CustomerID;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_Phone;
    // End of variables declaration//GEN-END:variables
}
