/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mb.view.forms;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import org.mb.controller.PaymentDAO;
import org.mb.controller.ProductDAO;
import org.mb.controller.SupplierDAO;
import org.mb.util.DBConnection;

/**
 *
 * @author QWERTY
 */
public class PurchaseReport extends javax.swing.JFrame {

    HashMap<String, Integer> smap, pmap;
    DateFormat df = new SimpleDateFormat("yyyy-MM-dd");

    /**
     * Creates new form PurchaseReport
     */
    public PurchaseReport() {
        initComponents();
        loadSupplier();
        loadProduct();
        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.MONTH, -1);
        jDateChooser_From.setDate(cal.getTime());
        jDateChooser_To.setDate(new Date());
    }

    public void loadSupplier() {
        SupplierDAO sDAO = new SupplierDAO();
        smap = sDAO.fetchSupplier();
        for (Map.Entry<String, Integer> m : smap.entrySet()) {
            jComboBox_Supplier.addItem(m.getKey());
        }
    }

    public void loadProduct() {
        ProductDAO pDAO = new ProductDAO();
        pmap = pDAO.fetchSupplier();
        for (Map.Entry<String, Integer> m : pmap.entrySet()) {
            jComboBox_Product.addItem(m.getKey());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_PurchaseReport = new javax.swing.JPanel();
        jButton_Report = new javax.swing.JButton();
        jDateChooser_From = new com.toedter.calendar.JDateChooser();
        jDateChooser_To = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_Supplier = new javax.swing.JComboBox<>();
        jComboBox_Product = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Purchase Report");

        jPanel_PurchaseReport.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel_PurchaseReportLayout = new javax.swing.GroupLayout(jPanel_PurchaseReport);
        jPanel_PurchaseReport.setLayout(jPanel_PurchaseReportLayout);
        jPanel_PurchaseReportLayout.setHorizontalGroup(
            jPanel_PurchaseReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_PurchaseReportLayout.setVerticalGroup(
            jPanel_PurchaseReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        jButton_Report.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Report.setText("Report");
        jButton_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ReportActionPerformed(evt);
            }
        });

        jDateChooser_From.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jDateChooser_To.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("To :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("From :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Supplier");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Product");

        jComboBox_Supplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_Supplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        jComboBox_Product.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_Product.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox_Product, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser_From, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser_To, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Report)
                .addGap(25, 25, 25))
            .addComponent(jPanel_PurchaseReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser_To, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser_From, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton_Report))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_Product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel_PurchaseReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ReportActionPerformed
        if (jDateChooser_From.getDate() == null
                || jDateChooser_To.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Please select both the dates From and To");
            return;
        }
        if (jDateChooser_From.getDate().compareTo(new Date()) > 0
                || jDateChooser_To.getDate().compareTo(new Date()) > 0) {
            JOptionPane.showMessageDialog(null, "please select the dates till current date");
            return;
        }
        if (jDateChooser_To.getDate().compareTo(jDateChooser_From.getDate()) < 0) {
            JOptionPane.showMessageDialog(null, "From date cant be after To date");
            return;
        }
        try {
            Connection con = DBConnection.getConnection();
            jPanel_PurchaseReport.removeAll();
            jPanel_PurchaseReport.repaint();
            jPanel_PurchaseReport.revalidate();

            String from = df.format(jDateChooser_From.getDate());
            String to = df.format(jDateChooser_To.getDate());

            HashMap map = new HashMap();
            map.put("from", from);
            map.put("to", to);
            //map.put("product",jTextField_Product.getText());
            //map.put("product","AND product.`name` LIKE '%p%' ");
            String sql_F = "SELECT amount from payments"
                    + " INNER JOIN purchases on payments.purchase_id = purchases.purchase_id"
                    + " INNER JOIN purchased_items on payments.purchase_id = purchased_items.purchase_id"
                    + " WHERE purchases.purchase_date BETWEEN '" + from + "' AND '" + to + "'";
            String sqlF = "SELECT\n"
                    + "     products.`name` AS product,\n"
                    + "     purchased_items.`quantity` AS quantity,\n"
                    + "     purchased_items.`purchase_price` AS price,\n"
                    + "     suppliers.`name` AS supplier,\n"
                    + "     purchases.`purchase_date` AS date\n"
                    + "FROM\n"
                    + "     `products` products INNER JOIN `purchased_items` purchased_items ON products.`product_id` = purchased_items.`product_id`\n"
                    + "     INNER JOIN `purchases` purchases ON purchased_items.`purchase_id` = purchases.`purchase_id`\n"
                    + "     INNER JOIN `suppliers` suppliers ON purchases.`supplier_id` = suppliers.`supplier_id`\n"
                    + "WHERE\n"
                    + "	purchased_items.`product_id` = products.`product_id`\n"
                    + " 	AND purchased_items.`purchase_id` = purchases.`purchase_id`\n"
                    + " 	AND purchases.`supplier_id` = suppliers.`supplier_id`";

            String sqlM = " AND purchases.`purchase_date` BETWEEN '" + from + "' AND '" + to + "'";
            if (jComboBox_Supplier.getSelectedIndex() != 0) {
                sqlM += " AND suppliers.`supplier_id` = "
                        + smap.get(jComboBox_Supplier.getSelectedItem().toString());
                sql_F+= " AND purchases.supplier_id = "
                        + smap.get(jComboBox_Supplier.getSelectedItem().toString());
            }
            if (jComboBox_Product.getSelectedIndex() != 0) {
                sqlM += " AND products.`product_id` = "
                        + pmap.get(jComboBox_Product.getSelectedItem().toString());
                sql_F+= " AND purchased_items.product_id = "
                        + pmap.get(jComboBox_Product.getSelectedItem().toString());
            }
            String sqlL = " GROUP BY purchased_items.`purchased_item_id` \n"
                    + "ORDER BY purchased_items.`purchased_item_id`";
            sql_F+=" GROUP BY payments.payment_id";
            System.out.println(sql_F);
            map.put("paid", new PaymentDAO().paid(sql_F));
            JasperDesign jd = JRXmlLoader.load("D:\\documents\\NetBeansProjects\\SalesRecordSystem\\src\\org\\mb\\view\\reports\\PurchaseReport.jrxml");
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(sqlF + sqlM + sqlL);
            jd.setQuery(updateQuery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, map, con);
            JRViewer jv = new JRViewer(jp);
            jPanel_PurchaseReport.setLayout(new BorderLayout());
            jPanel_PurchaseReport.add(jv);
            con.close();
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton_ReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Report;
    private javax.swing.JComboBox<String> jComboBox_Product;
    private javax.swing.JComboBox<String> jComboBox_Supplier;
    private com.toedter.calendar.JDateChooser jDateChooser_From;
    private com.toedter.calendar.JDateChooser jDateChooser_To;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel_PurchaseReport;
    // End of variables declaration//GEN-END:variables
}
