/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mb.view.forms;

import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import org.mb.controller.PaymentDAO;
import org.mb.controller.PurchaseDAO;
import org.mb.controller.PurchasedItemDAO;
import org.mb.controller.SupplierDAO;
import org.mb.model.Payment;
import org.mb.model.Purchase;
import org.mb.model.PurchasedItem;
import static org.mb.util.Session.uID;
import org.mb.view.panels.PurchasePanel;

/**
 *
 * @author QWERTY
 */
public class PurchaseForm extends javax.swing.JDialog {
    int purchase_id;
    DefaultTableModel purchase_model;
    JFrame hf;
    PurchasePanel pp;
    HashMap<String, Integer> smap;
    NumberFormat nf = NumberFormat.getInstance();

    public void setHomeFrame(JFrame hf) {
        this.hf = hf;
    }

    public void setPurchasePanel(PurchasePanel pp) {
        this.pp = pp;
    }
    
    public void setPurchase(int purchase_id){
        this.purchase_id=purchase_id; 
    }

    /**
     * Creates new form PurchaseForm
     */
    public PurchaseForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        nf.setMaximumFractionDigits(2);
        purchase_model = new DefaultTableModel(null, new String[]{"ID", "Product", "Quantity", "MFG Date", "EXP Date", "Price", "Total"});
        jTable_Purchase.setModel(purchase_model);
        loadSupplier();
    }

    public void loadSupplier() {
        SupplierDAO sDAO = new SupplierDAO();
        smap = sDAO.fetchSupplier();
        for (Map.Entry<String, Integer> m : smap.entrySet()) {
            jComboBox_Supplier.addItem(m.getKey());
        }
    }

    public int checkProduct(int productID) {
        for (int i = 0; i < jTable_Purchase.getRowCount(); i++) {
            if (jTable_Purchase.getValueAt(i, 0).toString().equalsIgnoreCase(productID + "")) {
                return i;
            }
        }
        return -1;
    }

    public void totalPrice() {
        int c = purchase_model.getRowCount();
        double total = 0;
        for (int i = 0; i < c; i++) {
            total += Double.parseDouble(purchase_model.getValueAt(i, 6).toString().replaceAll(",", ""));
        }
        jLabel_Total.setText(total + "");
        jTextField_Payment.setText("0.00");
        jLabel_PaymentError.setText(" ");
        jLabel_Due.setText((total + "").replaceAll(",", ""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox_Supplier = new javax.swing.JComboBox<>();
        jButton_AddProduct = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Purchase = new javax.swing.JTable();
        jLabel_Total = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_SavePurchase = new javax.swing.JButton();
        jTextField_Payment = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_Due = new javax.swing.JLabel();
        jLabel_PaymentError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Purchase Form");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Supplier :");

        jComboBox_Supplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_Supplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        jButton_AddProduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_AddProduct.setText("Add Product");
        jButton_AddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddProductActionPerformed(evt);
            }
        });

        jTable_Purchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Purchase.getTableHeader().setReorderingAllowed(false);
        jTable_Purchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_PurchaseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Purchase);

        jLabel_Total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Total.setText("0.00");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Total :");

        jButton_SavePurchase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_SavePurchase.setText("SAVE PURCHASE");
        jButton_SavePurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SavePurchaseActionPerformed(evt);
            }
        });

        jTextField_Payment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Payment.setText("0.00");
        jTextField_Payment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_PaymentKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Payment :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Due :");

        jLabel_Due.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Due.setText("0.00");

        jLabel_PaymentError.setForeground(java.awt.Color.red);
        jLabel_PaymentError.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 485, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel_PaymentError, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Total)
                            .addComponent(jLabel_Due)
                            .addComponent(jTextField_Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_AddProduct))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_SavePurchase)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_AddProduct)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel_Total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel_PaymentError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel_Due))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_SavePurchase)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddProductActionPerformed
        PurchaseItemForm p = new PurchaseItemForm(hf, true);
        p.setPurchaseForm(this);
        p.setVisible(true);
    }//GEN-LAST:event_jButton_AddProductActionPerformed

    private void jTable_PurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_PurchaseMouseClicked
        int row = jTable_Purchase.getSelectedRow();
        String[] options = {"Edit", "Delete", "Cancel"};
        int x = JOptionPane.showOptionDialog(null, "Choose an option.", "Purchase Option",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, null);
        if (x == 0) {
            PurchasedItem pob = new PurchasedItem();
            pob.setProduct_id(Integer.parseInt(jTable_Purchase.getValueAt(row, 0).toString()));
            pob.setProduct(jTable_Purchase.getValueAt(row, 1).toString());
            pob.setQuantity(Integer.parseInt(jTable_Purchase.getValueAt(row, 2).toString()));
            pob.setMfg_date(java.sql.Date.valueOf((jTable_Purchase.getValueAt(row, 3).toString())));
            pob.setExp_date(java.sql.Date.valueOf((jTable_Purchase.getValueAt(row, 4).toString())));
            pob.setPurchase_price(Double.parseDouble(jTable_Purchase.getValueAt(row, 5).toString()));

            PurchaseItemForm p = new PurchaseItemForm(hf, true);
            p.setPurchaseForm(this);
            p.setPurchasedItem(pob);
            p.setVisible(true);
        } else if (x == 1) {
            purchase_model.removeRow(row);
            totalPrice();
        }
    }//GEN-LAST:event_jTable_PurchaseMouseClicked

    private void jTextField_PaymentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PaymentKeyReleased
        if (jTextField_Payment.getText().equals("")) {
            jLabel_PaymentError.setText(" ");
            jLabel_Due.setText(jLabel_Total.getText());
            return;
        }

        try {
            double pmt = Double.parseDouble(jTextField_Payment.getText());
            double total = Double.parseDouble(jLabel_Total.getText());
            if (pmt > total) {
                jLabel_PaymentError.setText("Invalid Payment");
            } else {
                jLabel_Due.setText((nf.format(total - pmt) + "").replaceAll(",", ""));
                jLabel_PaymentError.setText(" ");
            }
        } catch (Exception ex) {
            jLabel_PaymentError.setText("Invalid Payment");
        }
    }//GEN-LAST:event_jTextField_PaymentKeyReleased

    private void jButton_SavePurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SavePurchaseActionPerformed
        if (!jLabel_PaymentError.getText().equals(" ")) {
            JOptionPane.showMessageDialog(null, "Sorry there are errors in the form");
            return;
        }
        if (jComboBox_Supplier.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, " Please select a supplier first ");
            return;
        }
        if(jTable_Purchase.getRowCount()==0){
            JOptionPane.showMessageDialog(null, " Please Add products to purchase first ");
            return;
        }

        //add new purchase
        Purchase pob = new Purchase();
        pob.setPayment_status(Double.parseDouble(jLabel_Due.getText()) == 0);
        pob.setSupplier_id(smap.get(jComboBox_Supplier.getSelectedItem().toString()));
        pob.setUpdated_by(uID);

        PurchaseDAO pDAO = new PurchaseDAO();
        int purchase_id = pDAO.addPurchase(pob);

        if (purchase_id != -1) {
            //add purchase items and stock
            ArrayList<PurchasedItem> pList = new ArrayList<>();
            int c = purchase_model.getRowCount();
            for (int row = 0; row < c; row++) {
                PurchasedItem ob = new PurchasedItem();
                ob.setProduct_id(Integer.parseInt(jTable_Purchase.getValueAt(row, 0).toString()));
                ob.setPurchase_id(purchase_id);
                ob.setQuantity(Integer.parseInt(jTable_Purchase.getValueAt(row, 2).toString()));
                ob.setPurchase_price(Double.parseDouble(jTable_Purchase.getValueAt(row, 5).toString()));
                ob.setMfg_date(java.sql.Date.valueOf((jTable_Purchase.getValueAt(row, 3).toString())));
                ob.setExp_date(java.sql.Date.valueOf((jTable_Purchase.getValueAt(row, 4).toString())));

                pList.add(ob);
            }
            PurchasedItemDAO piDAO = new PurchasedItemDAO();
            piDAO.addPurchasedItem(pList);

            //add payment
            Payment pmob = new Payment();
            PaymentDAO pmDAO = new PaymentDAO();
            pmob.setPurchase_id(purchase_id);
            pmob.setAmount(Double.parseDouble(jTextField_Payment.getText()));
            pmob.setUpdated_by(uID);
            pmDAO.addPayment(pmob);

            JOptionPane.showMessageDialog(null, " Purchase record success full");
            pp.loadData();
            dispose();
        }
    }//GEN-LAST:event_jButton_SavePurchaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PurchaseForm dialog = new PurchaseForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AddProduct;
    private javax.swing.JButton jButton_SavePurchase;
    private javax.swing.JComboBox<String> jComboBox_Supplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_Due;
    private javax.swing.JLabel jLabel_PaymentError;
    private javax.swing.JLabel jLabel_Total;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Purchase;
    private javax.swing.JTextField jTextField_Payment;
    // End of variables declaration//GEN-END:variables
}
