/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mb.view.forms;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import org.mb.controller.CustomerDAO;
import org.mb.controller.PaymentDAO;
import org.mb.controller.ProductDAO;
import org.mb.util.DBConnection;

/**
 *
 * @author QWERTY
 */
public class SalesReport extends javax.swing.JFrame {

    HashMap<String, Integer> cmap, pmap;
    DateFormat df = new SimpleDateFormat("yyyy-MM-dd");

    /**
     * Creates new form SalesReport
     */
    public SalesReport() {
        initComponents();
        loadCustomer();
        loadProduct();
        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.MONTH, -1);
        jDateChooser_From.setDate(cal.getTime());
        jDateChooser_To.setDate(new Date());
    }

    public void loadCustomer() {
        CustomerDAO cDAO = new CustomerDAO();
        cmap = cDAO.fetchCustomer();
        for (Map.Entry<String, Integer> m : cmap.entrySet()) {
            jComboBox_Customer.addItem(m.getKey());
        }
    }

    public void loadProduct() {
        ProductDAO pDAO = new ProductDAO();
        pmap = pDAO.fetchSupplier();
        for (Map.Entry<String, Integer> m : pmap.entrySet()) {
            jComboBox_Product.addItem(m.getKey());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_SalesReport = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jDateChooser_To = new com.toedter.calendar.JDateChooser();
        jDateChooser_From = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_Customer = new javax.swing.JComboBox<>();
        jComboBox_Product = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sales Report");

        jPanel_SalesReport.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel_SalesReportLayout = new javax.swing.GroupLayout(jPanel_SalesReport);
        jPanel_SalesReport.setLayout(jPanel_SalesReportLayout);
        jPanel_SalesReportLayout.setHorizontalGroup(
            jPanel_SalesReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        jPanel_SalesReportLayout.setVerticalGroup(
            jPanel_SalesReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDateChooser_To.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jDateChooser_From.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("To");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("From");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Customer");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Product");

        jComboBox_Customer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_Customer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        jComboBox_Product.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_Product.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_SalesReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_Customer, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox_Product, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser_From, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser_To, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_Product, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(531, 531, 531))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser_To, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox_Customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser_From, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(5, 5, 5)))
                        .addGap(1, 1, 1)
                        .addComponent(jPanel_SalesReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jDateChooser_From.getDate() == null
                || jDateChooser_To.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Please select both the dates From and To");
            return;
        }
        if (jDateChooser_From.getDate().compareTo(new Date()) > 0
                || jDateChooser_To.getDate().compareTo(new Date()) > 0) {
            JOptionPane.showMessageDialog(null, "please select the dates till current date");
            return;
        }
        if(jDateChooser_To.getDate().compareTo(jDateChooser_From.getDate())<0){
            JOptionPane.showMessageDialog(null, "From date cant be after To date");
            return;
        }
        try {
            Connection con = DBConnection.getConnection();
            jPanel_SalesReport.removeAll();
            jPanel_SalesReport.repaint();
            jPanel_SalesReport.revalidate();

            
            String from = df.format(jDateChooser_From.getDate());
            String to = df.format(jDateChooser_To.getDate());
            HashMap map = new HashMap();
            map.put("from", from);
            map.put("to", to);
            
            String sql_F = "SELECT amount from payments"
                    + " INNER JOIN sales on payments.sales_id = sales.sales_id"
                    + " INNER JOIN sales_items on payments.sales_id = sales_items.sales_id"
                    + " WHERE sales.sales_date BETWEEN '" + from + "' AND '" + to + "'";
            String sqlF = "SELECT\n"
                    + "     products.`name` AS product,\n"
                    + "     sales_items.`quantity` AS quantity,\n"
                    + "     sales_items.`sales_price` AS sales_price,\n"
                    + "     customers.`name` AS customer,\n"
                    + "     sales.`sales_date` AS date\n"
                    + "FROM\n"
                    + "     `products` products INNER JOIN `sales_items` sales_items ON products.`product_id` = sales_items.`product_id`\n"
                    + "     INNER JOIN `sales` sales ON sales_items.`sales_id` = sales.`sales_id`\n"
                    + "     INNER JOIN `customers` customers ON sales.`customer_id` = customers.`customer_id`\n"
                    + "WHERE\n"
                    + "	products.`product_id` = sales_items.`product_id`\n"
                    + "	AND sales_items.`sales_id` = sales.`sales_id`\n"
                    + "	AND sales.`customer_id` = customers.`customer_id`";
            String sqlM = " AND sales.`sales_date` BETWEEN '" + from + "' AND '" + to + "'";
            if (jComboBox_Customer.getSelectedIndex() != 0) {
                sqlM += " AND customers.`customer_id` = "
                        + cmap.get(jComboBox_Customer.getSelectedItem().toString());
                sql_F+= " AND sales.customer_id = "
                        + cmap.get(jComboBox_Customer.getSelectedItem().toString());
            }
            if (jComboBox_Product.getSelectedIndex() != 0) {
                sqlM += " AND products.`product_id` = "
                        + pmap.get(jComboBox_Product.getSelectedItem().toString());
                sql_F+= " AND sales_items.product_id = "
                        + pmap.get(jComboBox_Product.getSelectedItem().toString());
            }
            String sqlL = " GROUP BY sales_items.`sales_item_id` \n"
                    + "ORDER BY sales_items.`sales_item_id`";
            
            sql_F+=" GROUP BY payments.payment_id";
            System.out.println(sql_F);
            map.put("paid", new PaymentDAO().paid(sql_F));

            JasperDesign jd = JRXmlLoader.load("D:\\documents\\NetBeansProjects\\SalesRecordSystem\\src\\org\\mb\\view\\reports\\SalesReport.jrxml");
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(sqlF + sqlM + sqlL);
            jd.setQuery(updateQuery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, map, con);
            JRViewer jv = new JRViewer(jp);
            jPanel_SalesReport.setLayout(new BorderLayout());
            jPanel_SalesReport.add(jv);
            con.close();
        } catch (Exception ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox_Customer;
    private javax.swing.JComboBox<String> jComboBox_Product;
    private com.toedter.calendar.JDateChooser jDateChooser_From;
    private com.toedter.calendar.JDateChooser jDateChooser_To;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel_SalesReport;
    // End of variables declaration//GEN-END:variables
}
