/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mb.view.panels;

import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.*;
import org.mb.controller.CustomerDAO;
import org.mb.model.Customer;
import org.mb.view.forms.CustomerForm;

/**
 *
 * @author QWERTY
 */
public class CustomerPanel extends javax.swing.JPanel {

    DefaultTableModel model;
    JFrame hf = (JFrame) SwingUtilities.getWindowAncestor(this);

    /**
     * Creates new form CustomerPanel
     */
    public CustomerPanel() {
        initComponents();
        model = new DefaultTableModel(null, new String[]{"ID", "Name", "Address", "Phone", "Email"});
        jTable_Customer.setModel(model);
        loadData();
    }

    public void loadData() {
        clearModel();
        CustomerDAO cDAO = new CustomerDAO();
        ArrayList<Customer> cList = cDAO.fetchData();
        for (int i = 0; i < cList.size(); i++) {
            model.addRow(new Object[]{cList.get(i).getCustomer_id(),
                cList.get(i).getName(), cList.get(i).getAddress(),
                cList.get(i).getPhone(), cList.get(i).getEmail()});
        }
    }

    public void clearModel() {
        int c = model.getRowCount();
        for (int i = 0; i < c; i++) {
            model.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Customer = new javax.swing.JTable();
        jButton_RefreshCustomer = new javax.swing.JButton();
        jButton_AddCustomer = new javax.swing.JButton();

        jTable_Customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_Customer.getTableHeader().setReorderingAllowed(false);
        jTable_Customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_CustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Customer);

        jButton_RefreshCustomer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_RefreshCustomer.setText("Refresh");
        jButton_RefreshCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RefreshCustomerActionPerformed(evt);
            }
        });

        jButton_AddCustomer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_AddCustomer.setText("Add New");
        jButton_AddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_RefreshCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_AddCustomer)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_RefreshCustomer)
                    .addComponent(jButton_AddCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RefreshCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RefreshCustomerActionPerformed
        loadData();
    }//GEN-LAST:event_jButton_RefreshCustomerActionPerformed

    private void jButton_AddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddCustomerActionPerformed
        CustomerForm c = new CustomerForm(hf, true);
        c.setCustomerPanel(this);
        c.setVisible(true);
    }//GEN-LAST:event_jButton_AddCustomerActionPerformed

    private void jTable_CustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_CustomerMouseClicked
        int row = jTable_Customer.getSelectedRow();
        String[] options = {"Edit", "Delete", "Cancel"};
        int x = JOptionPane.showOptionDialog(null, "Choose an option.", "Customer Option",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, null);

        if (x == 0) {
            Customer cob = new Customer();
            cob.setCustomer_id(Integer.parseInt(jTable_Customer.getValueAt(row, 0).toString()));
            cob.setName(jTable_Customer.getValueAt(row, 1).toString());
            cob.setAddress(jTable_Customer.getValueAt(row, 2).toString());
            cob.setPhone(Long.parseLong(jTable_Customer.getValueAt(row, 3).toString()));
            cob.setEmail(jTable_Customer.getValueAt(row, 4).toString());
            
            CustomerForm c = new CustomerForm(hf, true);
            c.setCustomerPanel(this);
            c.setCustomer(cob);
            c.setVisible(true);
        }
    }//GEN-LAST:event_jTable_CustomerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AddCustomer;
    private javax.swing.JButton jButton_RefreshCustomer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Customer;
    // End of variables declaration//GEN-END:variables
}
