/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mb.view.panels;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import org.mb.controller.PurchaseDAO;
import org.mb.model.Purchase;
import org.mb.view.forms.PurchaseForm;
import org.mb.view.forms.PurchaseReport;

/**
 *
 * @author QWERTY
 */
public class PurchasePanel extends javax.swing.JPanel {
    DefaultTableModel model;
    JFrame hf = (JFrame) SwingUtilities.getWindowAncestor(this);
    /**
     * Creates new form PurchasePanel
     */
    public PurchasePanel() {
        initComponents();
        model = new DefaultTableModel(null,new String[]{"ID", "Payment Status", "Purchase Date", "Supplier"});
        jTable_Purchase.setModel(model);
        loadData();
    }
    
    public void loadData(){
        clearModel();
        PurchaseDAO pDAO =new PurchaseDAO();
        ArrayList<Purchase> pList = pDAO.fetchData();
        for (int i = 0; i < pList.size(); i++) {
            model.addRow(new Object[]{pList.get(i).getPurchase_id(),
                pList.get(i).isPayment_status(),
                pList.get(i).getPurchase_date(), pList.get(i).getSupplier()});
        }
    }
    
    public void clearModel() {
        int c = model.getRowCount();
        for (int i = 0; i < c; i++) {
            model.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Purchase = new javax.swing.JTable();
        jButton_RefreshPurchase = new javax.swing.JButton();
        jButton_ViewPurchaseReport = new javax.swing.JButton();
        jButton_NewPurchase = new javax.swing.JButton();

        jTable_Purchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Purchase.getTableHeader().setReorderingAllowed(false);
        jTable_Purchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_PurchaseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Purchase);

        jButton_RefreshPurchase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_RefreshPurchase.setText("Refresh");
        jButton_RefreshPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RefreshPurchaseActionPerformed(evt);
            }
        });

        jButton_ViewPurchaseReport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_ViewPurchaseReport.setText("View Report");
        jButton_ViewPurchaseReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ViewPurchaseReportActionPerformed(evt);
            }
        });

        jButton_NewPurchase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_NewPurchase.setText("New Purchase");
        jButton_NewPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NewPurchaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_RefreshPurchase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_ViewPurchaseReport)
                .addGap(32, 32, 32)
                .addComponent(jButton_NewPurchase)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_RefreshPurchase)
                    .addComponent(jButton_ViewPurchaseReport)
                    .addComponent(jButton_NewPurchase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RefreshPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RefreshPurchaseActionPerformed
        loadData();
    }//GEN-LAST:event_jButton_RefreshPurchaseActionPerformed

    private void jButton_ViewPurchaseReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ViewPurchaseReportActionPerformed
        PurchaseReport p =new PurchaseReport();
        p.setVisible(true);
    }//GEN-LAST:event_jButton_ViewPurchaseReportActionPerformed

    private void jButton_NewPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NewPurchaseActionPerformed
        PurchaseForm p =new PurchaseForm(hf, true);
        p.setHomeFrame(hf);
        p.setPurchasePanel(this);
        p.setVisible(true);
    }//GEN-LAST:event_jButton_NewPurchaseActionPerformed

    private void jTable_PurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_PurchaseMouseClicked
        int row = jTable_Purchase.getSelectedRow();
        int purchase_id = Integer.parseInt(jTable_Purchase.getValueAt(row, 0).toString());
        PurchaseForm p =new PurchaseForm(hf, true);
        p.setHomeFrame(hf);
        p.setPurchasePanel(this);
        p.setPurchase(purchase_id);
        p.setVisible(true);
        
    }//GEN-LAST:event_jTable_PurchaseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_NewPurchase;
    private javax.swing.JButton jButton_RefreshPurchase;
    private javax.swing.JButton jButton_ViewPurchaseReport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Purchase;
    // End of variables declaration//GEN-END:variables
}
