/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mb.view.panels;

import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.*;
import org.mb.controller.SupplierDAO;
import org.mb.model.Supplier;
import org.mb.view.forms.SupplierForm;

/**
 *
 * @author QWERTY
 */
public class SupplierPanel extends javax.swing.JPanel {
    
    DefaultTableModel model;
    JFrame hf = (JFrame) SwingUtilities.getWindowAncestor(this);

    /**
     * Creates new form SupplierPanel
     */
    public SupplierPanel() {
        initComponents();
        model = new DefaultTableModel(null, new String[]{"ID", "Name", "Address", "Phone", "Email"});
        jTable_Supplier.setModel(model);
        loadData();
    }
    
    public void loadData() {
        clearModel();
        SupplierDAO sDAO = new SupplierDAO();
        ArrayList<Supplier> sList = sDAO.fetchData();
        for (int i = 0; i < sList.size(); i++) {
            model.addRow(new Object[]{sList.get(i).getSupplier_id(),
                sList.get(i).getName(), sList.get(i).getAddress(),
                sList.get(i).getPhone(), sList.get(i).getEmail()});
        }
    }
    
    public void clearModel() {
        int c = model.getRowCount();
        for (int i = 0; i < c; i++) {
            model.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_RefreshSupplier = new javax.swing.JButton();
        jButton_AddSupplier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Supplier = new javax.swing.JTable();

        jButton_RefreshSupplier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_RefreshSupplier.setText("Refresh");
        jButton_RefreshSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RefreshSupplierActionPerformed(evt);
            }
        });

        jButton_AddSupplier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_AddSupplier.setText("Add New");
        jButton_AddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddSupplierActionPerformed(evt);
            }
        });

        jTable_Supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Supplier.getTableHeader().setReorderingAllowed(false);
        jTable_Supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_SupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Supplier);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_RefreshSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_AddSupplier)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_RefreshSupplier)
                    .addComponent(jButton_AddSupplier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RefreshSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RefreshSupplierActionPerformed
        loadData();
    }//GEN-LAST:event_jButton_RefreshSupplierActionPerformed

    private void jButton_AddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddSupplierActionPerformed
        SupplierForm s = new SupplierForm(hf, true);
        s.setSupplierPanel(this);
        s.setVisible(true);
    }//GEN-LAST:event_jButton_AddSupplierActionPerformed

    private void jTable_SupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_SupplierMouseClicked
        int row = jTable_Supplier.getSelectedRow();
        String[] options = {"Edit", "Delete", "Cancel"};
        int x = JOptionPane.showOptionDialog(null, "Choose an option.", "Supplier Option",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, null);
        
        if (x == 0) {
            Supplier sob = new Supplier();
            sob.setSupplier_id(Integer.parseInt(jTable_Supplier.getValueAt(row, 0).toString()));
            sob.setName(jTable_Supplier.getValueAt(row, 1).toString());
            sob.setAddress(jTable_Supplier.getValueAt(row, 2).toString());
            sob.setPhone(Long.parseLong(jTable_Supplier.getValueAt(row, 3).toString()));
            sob.setEmail(jTable_Supplier.getValueAt(row, 4).toString());
            
            SupplierForm s = new SupplierForm(hf, true);
            s.setSupplierPanel(this);
            s.setSupplier(sob);
            s.setVisible(true);
        }
    }//GEN-LAST:event_jTable_SupplierMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AddSupplier;
    private javax.swing.JButton jButton_RefreshSupplier;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Supplier;
    // End of variables declaration//GEN-END:variables
}
