/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mb.view;

import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.mb.controller.ProductDAO;
import org.mb.model.Product;
import org.mb.view.forms.CategoryForm;

/**
 *
 * @author QWERTY
 */
public class HomeFrame extends javax.swing.JFrame {

    DefaultTableModel productModel;

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        productModel = new DefaultTableModel(null, new String[]{"ID", "Name", "Description", "Sales Price", "Category", "Quantity"}
        ) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable_Product.setModel(productModel);
        loadProductData();
    }

    public void loadProductData() {
        clearProductModel();
        ProductDAO pDAO = new ProductDAO();
        ArrayList<Product> pList = pDAO.fetchData();
        for (int i = 0; i < pList.size(); i++) {

            productModel.addRow(new Object[]{pList.get(i).getProduct_id(),
                pList.get(i).getName(), pList.get(i).getDescription(),
                pList.get(i).getSales_price(), pList.get(i).getCategory(),
                pList.get(i).getQuantity()});
        }
    }

    public void clearProductModel() {
        int c = productModel.getRowCount();
        for (int i = 0; i < c; i++) {
            productModel.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ProductPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Product = new javax.swing.JTable();
        jButton_AddProduct = new javax.swing.JButton();
        jButton_RefreshProduct = new javax.swing.JButton();
        jButton_Category = new javax.swing.JButton();
        customerPanel1 = new org.mb.view.panels.CustomerPanel();
        supplierPanel1 = new org.mb.view.panels.SupplierPanel();
        purchasePanel2 = new org.mb.view.panels.PurchasePanel();
        salesPanel1 = new org.mb.view.panels.SalesPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sales Record System");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 10, 0));

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTable_Product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Product.getTableHeader().setReorderingAllowed(false);
        jTable_Product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Product);

        jButton_AddProduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_AddProduct.setText("Add New");
        jButton_AddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddProductActionPerformed(evt);
            }
        });

        jButton_RefreshProduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_RefreshProduct.setText("Refresh");
        jButton_RefreshProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RefreshProductActionPerformed(evt);
            }
        });

        jButton_Category.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Category.setText("Category");
        jButton_Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductPanelLayout = new javax.swing.GroupLayout(ProductPanel);
        ProductPanel.setLayout(ProductPanelLayout);
        ProductPanelLayout.setHorizontalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_RefreshProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Category)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_AddProduct)
                .addContainerGap())
        );
        ProductPanelLayout.setVerticalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_AddProduct)
                    .addComponent(jButton_RefreshProduct)
                    .addComponent(jButton_Category))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Product", ProductPanel);
        jTabbedPane1.addTab("Customer", customerPanel1);
        jTabbedPane1.addTab("Supplier", supplierPanel1);
        jTabbedPane1.addTab("Purchase", purchasePanel2);
        jTabbedPane1.addTab("Sales", salesPanel1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(197, 197, 197))
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RefreshProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RefreshProductActionPerformed
        loadProductData();
    }//GEN-LAST:event_jButton_RefreshProductActionPerformed

    private void jButton_AddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddProductActionPerformed
        ProductForm p = new ProductForm(this, true);
        p.setHomeFrame(this);
        p.setVisible(true);
    }//GEN-LAST:event_jButton_AddProductActionPerformed

    private void jTable_ProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ProductMouseClicked
        int row = jTable_Product.getSelectedRow();
        String[] options = {"Edit", "Delete", "Cancel"};
        int x = JOptionPane.showOptionDialog(null, "Choose an option.", "Product Option",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, null);
        if (x == 0) {
            Product pob = new Product();
            pob.setProduct_id(Integer.parseInt(jTable_Product.getValueAt(row, 0).toString()));
            pob.setName(jTable_Product.getValueAt(row, 1).toString());
            pob.setDescription(jTable_Product.getValueAt(row, 2).toString());
            pob.setSales_price(Double.parseDouble(jTable_Product.getValueAt(row, 3).toString()));
            pob.setCategory(jTable_Product.getValueAt(row, 4).toString());

            ProductForm p = new ProductForm(this, true);
            p.setHomeFrame(this);
            p.setProduct(pob);
            p.setVisible(true);
        }

    }//GEN-LAST:event_jTable_ProductMouseClicked

    private void jButton_CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CategoryActionPerformed
        CategoryForm c = new CategoryForm();
        c.setVisible(true);
    }//GEN-LAST:event_jButton_CategoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ProductPanel;
    private org.mb.view.panels.CustomerPanel customerPanel1;
    private javax.swing.JButton jButton_AddProduct;
    private javax.swing.JButton jButton_Category;
    private javax.swing.JButton jButton_RefreshProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_Product;
    private org.mb.view.panels.PurchasePanel purchasePanel2;
    private org.mb.view.panels.SalesPanel salesPanel1;
    private org.mb.view.panels.SupplierPanel supplierPanel1;
    // End of variables declaration//GEN-END:variables
}
