/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mb.view;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.mb.controller.CategoryDAO;
import org.mb.controller.ProductDAO;
import org.mb.model.Product;

/**
 *
 * @author QWERTY
 */
public class ProductForm extends javax.swing.JDialog {

    HashMap<String, Integer> cmap;
    HomeFrame hf;
    Product pob;

    public void setHomeFrame(HomeFrame hf) {
        this.hf = hf;
    }

    public void setProduct(Product pob) {
        this.pob = pob;
        jTextField_ProductID.setText(pob.getProduct_id() + "");
        jTextField_Name.setText(pob.getName());
        jTextField_Description.setText(pob.getDescription());
        jTextField_SalesPrice.setText(pob.getSales_price() + "");
        jComboBox_Category.setSelectedItem(pob.getCategory());
    }

    /**
     * Creates new form ProductForm
     */
    public ProductForm(javax.swing.JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadCategory();
    }

    public void loadCategory() {
        CategoryDAO cDAO = new CategoryDAO();
        cmap = cDAO.fetchCategory();
        for (Map.Entry<String, Integer> m : cmap.entrySet()) {
            jComboBox_Category.addItem(m.getKey());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_ProductID = new javax.swing.JTextField();
        jButton_SaveProduct = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_Description = new javax.swing.JTextField();
        jTextField_SalesPrice = new javax.swing.JTextField();
        jComboBox_Category = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel_SalesPriceError = new javax.swing.JLabel();
        jLabel_NameError = new javax.swing.JLabel();
        jLabel_DescriptionError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Product Form");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Product ID :");

        jTextField_ProductID.setEditable(false);
        jTextField_ProductID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton_SaveProduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_SaveProduct.setText("SAVE");
        jButton_SaveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveProductActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Description :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Sales Price :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Category :");

        jTextField_Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_NameKeyReleased(evt);
            }
        });

        jTextField_Description.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Description.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_DescriptionKeyReleased(evt);
            }
        });

        jTextField_SalesPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_SalesPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_SalesPriceKeyReleased(evt);
            }
        });

        jComboBox_Category.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Product Form");

        jLabel_SalesPriceError.setForeground(java.awt.Color.red);
        jLabel_SalesPriceError.setText(" ");

        jLabel_NameError.setForeground(java.awt.Color.red);
        jLabel_NameError.setText(" ");

        jLabel_DescriptionError.setForeground(java.awt.Color.red);
        jLabel_DescriptionError.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel6)
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_SaveProduct)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_DescriptionError, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel_SalesPriceError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_Name)
                                .addComponent(jTextField_Description)
                                .addComponent(jTextField_SalesPrice)
                                .addComponent(jComboBox_Category, 0, 150, Short.MAX_VALUE)
                                .addComponent(jTextField_ProductID)
                                .addComponent(jLabel_NameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_ProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_NameError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_DescriptionError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_SalesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_SalesPriceError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_SaveProduct)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SaveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveProductActionPerformed
        //check errors
        if (!(jLabel_NameError.getText().equals(" ")
                && jLabel_DescriptionError.getText().equals(" ")
                && jLabel_SalesPriceError.getText().equals(" "))) {
            JOptionPane.showMessageDialog(null, "Sorry there are errors in the form");
            return;
        }
        if (new ProductDAO().checkProduct(jTextField_Name.getText())
                && pob == null) {
            JOptionPane.showMessageDialog(null, "Sorry the product is already added");
            return;
        }
        if(jTextField_Name.getText().equals("")
                || jTextField_Description.getText().equals("")
                || jTextField_SalesPrice.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill all the fields first");
            return;
        }

        //get input values
        String name = jTextField_Name.getText();
        String description = jTextField_Description.getText();
        double sales_price = Double.parseDouble(jTextField_SalesPrice.getText());
        int category_id = cmap.get(jComboBox_Category.getSelectedItem().toString());;

        //set input values into model class "Product" object
        Product ob = new Product();
        ob.setName(name);
        ob.setDescription(description);
        ob.setSales_price(sales_price);
        ob.setCategory_id(category_id);

        //handover this model object to controller class "CustomerDAO"
        ProductDAO pDAO = new ProductDAO();
        if (pob == null) {
            pDAO.addProduct(ob);
        } else {
            ob.setProduct_id(pob.getProduct_id());
            pDAO.updateProduct(ob);
        }

        hf.loadProductData();
        dispose();
    }//GEN-LAST:event_jButton_SaveProductActionPerformed

    private void jTextField_SalesPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SalesPriceKeyReleased

        try {
            double x = Double.parseDouble(jTextField_SalesPrice.getText());
            jLabel_SalesPriceError.setText(" ");
        } catch (Exception ex) {
            jLabel_SalesPriceError.setText("Invalid Price");
        }
    }//GEN-LAST:event_jTextField_SalesPriceKeyReleased

    private void jTextField_DescriptionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_DescriptionKeyReleased

        if (jTextField_Description.getText().equals("")) {
            jLabel_DescriptionError.setText("Description cant be empty");
        } else {
            jLabel_DescriptionError.setText(" ");
        }
    }//GEN-LAST:event_jTextField_DescriptionKeyReleased

    private void jTextField_NameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NameKeyReleased
        if (jTextField_Name.getText().equals("")) {
            jLabel_NameError.setText("Name cant be empty");
        } else {
            jLabel_NameError.setText(" ");
        }
    }//GEN-LAST:event_jTextField_NameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProductForm dialog = new ProductForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_SaveProduct;
    private javax.swing.JComboBox<String> jComboBox_Category;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_DescriptionError;
    private javax.swing.JLabel jLabel_NameError;
    private javax.swing.JLabel jLabel_SalesPriceError;
    private javax.swing.JTextField jTextField_Description;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_ProductID;
    private javax.swing.JTextField jTextField_SalesPrice;
    // End of variables declaration//GEN-END:variables
}
